import { Navbar } from "@/components";
import "./globals.css";
import { Barlow, Barlow_Condensed, Bellefair } from "next/font/google";
import { WebProvider } from "@/utilities/WebContext";

const barlow = Barlow({
  subsets: ["latin"],
  weight: "400",
  variable: "--barlow",
});
const barlow_con_reg = Barlow_Condensed({
  subsets: ["latin"],
  weight: "400",
  variable: "--barlow_con_reg",
});
const barlow_con_bold = Barlow_Condensed({
  subsets: ["latin"],
  weight: "700",
  variable: "--barlow_con_bold",
});
const bellefar = Bellefair({
  subsets: ["latin"],
  weight: "400",
  variable: "--bellefar",
});

export const metadata = {
  title: "Frontend Mentor | Space tourism website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${barlow.variable} ${barlow_con_reg.variable} ${barlow_con_bold.variable} ${bellefar.variable} bg-slate-950`}
    >
      <body className="w-screen min-h-screen relative">
        <WebProvider>
          <>
            <Navbar />
            {children}
          </>
        </WebProvider>
      </body>
    </html>
  );
}
